using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class CatNav : MonoBehaviour
{
    private NavMeshAgent _agent;
    public GameObject Player;
    public float EnemyDistanceRun = 1.0f;
    public Animator anim;

    private void Awake()
    {
        _agent = GetComponent<NavMeshAgent>();
    }
   

    private void Update()
    {
        float distance = Vector3.Distance(transform.position, Player.transform.position);

        if(distance < EnemyDistanceRun)
        {
            Vector3 dirToPlayer = transform.position - Player.transform.position;
            Vector3 newPos = transform.position + dirToPlayer;
            anim.Play("Run");
            _agent.SetDestination(newPos);
        }
    }
}